{% set name = "pytest-flake8" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d85efaafbdb9580791cfa8671799dd40d482fc30bd4476c1ca5efd661e751333

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - flake8 >=3.5
    - pytest >=3.5

test:
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help

about:
  home: https://github.com/tholo/pytest-flake8
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pytest plugin to check FLAKE8 requirements

extra:
  recipe-maintainers:
    - kynan
    - dopplershift
