{% set name = "pytest-flake8" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_flake8-{{ version }}.tar.gz
  sha256: 88fb35562ce32d915c6ba41ef0d5e1cfcdd8ff884a32b7d46aa99fc77a3d1fe6

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install --no-deps --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python
    - setuptools >=61.2
    - pip
    - setuptools-scm >=3.4.1
  run:
    - python
    - flake8 >=4.0
    - pytest >=7.0
  run_constrained:
    - pytest-checkdocs >=2.4
    - pytest-enabler >=2.2

test:
  requires:
    - py
    - pip
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help
    - pip check

about:
  home: https://github.com/tholo/pytest-flake8
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pytest plugin to check FLAKE8 requirements
  description: pytest plugin to run flake8
  doc_url: https://github.com/tholo/pytest-flake8/blob/master/README.rst
  dev_url: https://github.com/tholo/pytest-flake8

extra:
  recipe-maintainers:
    - kynan
    - dopplershift