{% set name = "pytest-flake8" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2c71fb6d469bae076a01c43d4a83485d740db6a8a00bad77e0657ed035e98d4

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - configparser  # [py27]
    - enum34  # [py27]
    - flake8 >=3.5
    - pytest >=3.2

test:
  imports:
    - pytest_flake8
  commands:
    - pytest --flake8 --help

about:
  home: https://github.com/tholo/pytest-flake8
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'pytest plugin to check FLAKE8 requirements'

extra:
  recipe-maintainers:
    - kynan
    - dopplershift
