travis:
  secure:
    BINSTAR_TOKEN: 4efjFRSUQ9Gv3zIzJXvk/3XIpVZoarQ1YeRmtxUgGgWwbTRVpUrUs4uvmi0WypRn34tEfw+oP/VUffvpOVED1DOfkIk8ZCL29r/pJB4K4JTioQo8AbFARdoTAZ/RMVRqSsCBELLgtY5oQHMpMPLJWbOI0a0UDHcw6NjJtDAgAoF0iulPQaOsolZ5WPX35fAV/XyOCAN7SJtC27knTWgkqv47g0LWHGH4g8Ny7KoycvKEKa0+Efb9NHJedqOBAqmcZxdr+wzQReQKExzb2fQ86t7zDvTYuQc5V+AbmAAvxH7LzolgVVj6fMOH64nbQx/jCpaGYRo9nO1nCXqSluEe3PBevYPdCjaEmsc4SlPnabiGKPn5wBjb7VSF5ZjjHBd+8wC7c2yOLA2YCMF/H2xMGnFUwlSwcaETfOEULm3pYmM2BcZfa1D2Ut46UBV4jhenAegnq0+MYzyZSWZE/euo3Za6GqEaEtrZohsUA0I67JVOHLYkXCfXs0PqRWiObm9FtxSziowkuvopW9Na+AdogvdZL3Y2GgH6wlFVVccal/g/B3hogqNTBbus1lWI0xKYI7XzGrIfng/5fgd0or37y3Qgcjm69qBulTdL2KSZZNO4bDnQr2TQz/Z4R+Rhg6Cw7Xr6hed9VOcXM6ieIOvMBgVb1eW9DgU7ym8SXhR01QQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
