appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VhOxr8LXUwZor9KRf7p3vNiMqPpUcPI5AvOQiKa0B6OoGpEEdzo7BWXO1oqMavPN45dUhrqVge01KTYvrWsaOpJQ+W13QGN4mlzmKBlSHRiZpvq9AvQpa/Qz5GFVnbqWuR6irhDNfmp47rKPEbsgCvyuuYPCBK/yl5Djo+89CFdZ90Qo/Io/krsJwY3iF5Ep4Mw28dxFk25u5rXpCFhvKnLrKe4G3lRmHRuHZ6+YmKV09NReBCoCA1hQ8oHiuj3S4kMzHceLbDFl89j32/V3oWvlQ7XoxVabhdNHW4+Qs+0+cywe1eDvJ+cNgjy0cYBSBcN1ByshYHYhbpzDVGLPMtSvtHR/TTvt2fGLMgiRPp+CYU9PRVBbyvGPlgbqjrGDFpd8LlEYLexSxc0F7MMkwJNZhPraFPLEo4eXy10iSfKCvH44XzANYjcXKKx1KfyCP0k58ytUKlCLIA4nTQYk2hMOxzF8wKdmTp/Uzb4S0hCKGA5CP42+CRUfeHR8MbTMioNYg8S7ox+C6uoqfDa/xDJCbHhw9xij0TPsY4DjaAhovRa9jjnXSEgn/g8XbQ6LFwVfOaSa7PYbpm+nIlFMfYdISdI3sHArnhLM6juQb6R5qw7rUZF83GwJslJ2bEn/zcnisSNVe2pbZ1FwedhTlafo3AOzScV0DQC6ZGfJ3qE=}
