travis:
  secure:
    BINSTAR_TOKEN: tkIZkk3tuHjQOMC6TbnUL6pHRoDPiKBurcM9iy9564RN9CbBbk7NIzpozmLCwqxYYPzFgN+JGt/HTUM6iGIzPXabJgLXUikJ6nBknra4vg9mcuXprCJu0F5IwyaEw+CBCJEHSgFMcsBHau+TQ6996aJ1MOAgRAIqgawzAtVUVEm5hlRdAuwP9ITVc9otg0fGlJwtFEessMv9Nhhn8hsQRKPiGd5cDOExSI/CAa8K+J1xK1/M+Va4LU1xsWnEmzlHdVxqmxLbFQkvrwxoXMQ4zavrs0I0EXgRDWnwDFE6piHwnNb4cqZZMyWdmDAD5U0CquZEbZCMVBr1JJOS7zf7nu5jLR8/vcOytg7AnWuImBv3u4m9Tv2Ot4285IAJUwAapraBBn2PUheCcmxf5lKDRgdSEWioVDdNqRjNdaGJy3rdXWtURZH1o5zhFyjf/ZjjjoJuRiqBej4VOS7zBGc+6aPFs2kPqEBvT1DXlryKjTvAWInI1Zt45hdrjVD1Gp85Ef2FN12mcRjakB8VsexAbxk3LHPkXygFJk+eijv2CYJqVAYnVYWOGpvne/EYBGOEdSdW3g3s/jKklX7lRKoMA6UQ9X0j/gCY1qIAsUfe9TxKryRHoFiPYQljn6Q+K23cM0UDivolYeHdJESlVhPWEm1IVadubhUhcSjtlMO5Px4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
